interface IImages {
  id: number,
  src: string,
  title: string,
  desc: string,
  orientation?: "landscape" | "portrait",
}
export const images: IImages[] = [
  {
    id: 1,
    src: "/public/images/DSC_0069.jpg",
    title: "DSC_0069.jpg",
    desc: "Gałązka",
    orientation: "portrait",
  },
  {
    id: 2,
    src: "/public/images/DSC_0092.jpg",
    title: "DSC_0092.jpg",
    desc: "Koniczyna łąkowa (Trifolium pratense L.)",
  },
  {
    id: 3,
    src: "/public/images/DSC_0115.jpg",
    title: "DSC_0115.jpg",
    desc: "Niecierpek Waleriana",
  },
  {
    id: 4,
    src: "/public/images/DSC_0116.jpg",
    title: "DSC_0116.jpg",
    desc: "Liść",
  },
  {
    id: 5,
    src: "/public/images/DSC_0133.jpg",
    title: "DSC_0133.jpg",
    desc: "Liść",
    orientation: "portrait",
  },
  {
    id: 6,
    src: "/public/images/DSC_0135.jpg",
    title: "DSC_0135.jpg",
    desc: "Łątka dzieweczka (Coenagrion puella)",
  },
  {
    id: 7,
    src: "/public/images/DSC_0135_a.jpg",
    title: "DSC_0135_a.jpg",
    desc: "Mniszek pospolity",
  },
  {
    id: 8,
    src: "/public/images/DSC_0139.jpg",
    title: "DSC_0139.jpg",
    desc: "DESCRIPTION",
  },
  {
    id: 9,
    src: "/public/images/DSC_0144.jpg",
    title: "DSC_0144.jpg",
    desc: "DESCRIPTION",
  },
  {
    id: 10,
    src: "/public/images/DSC_0148.jpg",
    title: "DSC_0148.jpg",
    desc: "DESCRIPTION",
  },
  {
    id: 11,
    src: "/public/images/DSC_0152.jpg",
    title: "DSC_0152.jpg",
    desc: "DESCRIPTION",
    orientation: "portrait",
  },
  {
    id: 12,
    src: "/public/images/DSC_0154.jpg",
    title: "DSC_0154.jpg",
    desc: "DESCRIPTION",
    orientation: "portrait",
  },
  {
    id: 13,
    src: "/public/images/DSC_0162.jpg",
    title: "DSC_0162.jpg",
    desc: "DESCRIPTION",
  },
  {
    id: 14,
    src: "/public/images/DSC_0167.jpg",
    title: "DSC_0167.jpg",
    desc: "DESCRIPTION",
    orientation: "portrait",
  },
  {
    id: 15,
    src: "/public/images/DSC_0170.jpg",
    title: "DSC_0170.jpg",
    desc: "DESCRIPTION",
    orientation: "portrait",
  },
  {
    id: 16,
    src: "/public/images/DSC_0172.jpg",
    title: "DSC_0172.jpg",
    desc: "DESCRIPTION",
  },
  {
    id: 17,
    src: "/public/images/DSC_0178.jpg",
    title: "DSC_0178.jpg",
    desc: "DESCRIPTION",
    orientation: "portrait",
  },
  {
    id: 18,
    src: "/public/images/DSC_0178_a.jpg",
    title: "DSC_0178_a.jpg",
    desc: "DESCRIPTION",
  },
  {
    id: 19,
    src: "/public/images/DSC_0180.jpg",
    title: "DSC_0180.jpg",
    desc: "DESCRIPTION",
  },
  {
    id: 20,
    src: "/public/images/DSC_0186.jpg",
    title: "DSC_0186.jpg",
    desc: "DESCRIPTION",
    orientation: "portrait",
  },
  {
    id: 21,
    src: "/public/images/DSC_0189.jpg",
    title: "DSC_0189.jpg",
    desc: "DESCRIPTION",
  },
  {
    id: 22,
    src: "/public/images/DSC_0191.jpg",
    title: "DSC_0191.jpg",
    desc: "DESCRIPTION",
  },
  {
    id: 23,
    src: "/public/images/DSC_0190.jpg",
    title: "DSC_0190.jpg",
    desc: "DESCRIPTION",
  },
];
