interface IImages {
  id: number,
  src: string,
  title: string,
  desc: string,
  orientation?: "landscape" | "portrait",
}
export const images: IImages[] = [
  {
    id: 1,
    src: "/public/images/_ (1).JPG",
    title: "TITLE",
    desc: "DESCRIPTION",
  },
  {
    id: 2,
    src: "/public/images/_ (2).JPG",
    title: "TITLE",
    desc: "DESCRIPTION",
    orientation: "portrait",
  },
  {
    id: 3,
    src: "/public/images/_ (3).JPG",
    title: "TITLE",
    desc: "DESCRIPTION",
  },
  {
    id: 4,
    src: "/public/images/_ (4).JPG",
    title: "TITLE",
    desc: "DESCRIPTION",
  },
  {
    id: 5,
    src: "/public/images/_ (5).JPG",
    title: "TITLE",
    desc: "DESCRIPTION",
  },
  {
    id: 6,
    src: "/public/images/_ (6).JPG",
    title: "TITLE",
    desc: "DESCRIPTION",
    orientation: "portrait",
  },
  {
    id: 7,
    src: "/public/images/_ (7).JPG",
    title: "TITLE",
    desc: "DESCRIPTION",
  },
  {
    id: 8,
    src: "/public/images/_ (8).JPG",
    title: "TITLE",
    desc: "DESCRIPTION",
  },
  {
    id: 9,
    src: "/public/images/_ (9).JPG",
    title: "TITLE",
    desc: "DESCRIPTION",
  },
  {
    id: 10,
    src: "/public/images/_ (10).JPG",
    title: "TITLE",
    desc: "DESCRIPTION",
    orientation: "portrait",
  },
  {
    id: 11,
    src: "/public/images/_ (11).JPG",
    title: "TITLE",
    desc: "DESCRIPTION",
  },
  {
    id: 12,
    src: "/public/images/_ (12).JPG",
    title: "TITLE",
    desc: "DESCRIPTION",
  },
  {
    id: 13,
    src: "/public/images/_ (13).JPG",
    title: "TITLE",
    desc: "DESCRIPTION",
  },
  {
    id: 14,
    src: "/public/images/_ (14).JPG",
    title: "TITLE",
    desc: "DESCRIPTION",
  },
  {
    id: 15,
    src: "/public/images/_ (15).JPG",
    title: "TITLE",
    desc: "DESCRIPTION",
  },
  {
    id: 16,
    src: "/public/images/_ (16).JPG",
    title: "TITLE",
    desc: "DESCRIPTION",
    orientation: "portrait",
  },
  {
    id: 17,
    src: "/public/images/_ (17).JPG",
    title: "TITLE",
    desc: "DESCRIPTION",
    orientation: "portrait",
  },
  {
    id: 18,
    src: "/public/images/_ (18).JPG",
    title: "TITLE",
    desc: "DESCRIPTION",
  },
  {
    id: 19,
    src: "/public/images/_ (19).JPG",
    title: "TITLE",
    desc: "DESCRIPTION",
    orientation: "portrait",
  },
  {
    id: 20,
    src: "/public/images/_ (20).JPG",
    title: "TITLE",
    desc: "DESCRIPTION",
    orientation: "portrait",
  },
  {
    id: 21,
    src: "/public/images/_ (21).JPG",
    title: "TITLE",
    desc: "DESCRIPTION",
  },
  {
    id: 22,
    src: "/public/images/_ (22).JPG",
    title: "TITLE",
    desc: "DESCRIPTION",
    orientation: "portrait",
  },
  {
    id: 23,
    src: "/public/images/_ (23).JPG",
    title: "TITLE",
    desc: "DESCRIPTION",
  },
];
